name: model
channels:
- conda-forge
- districtdatalabs
- rapidsai
dependencies:
- python>=3.7
- category_encoders
- configparser
- cython
- dataclasses
- eli5
- glob2
- imbalanced-learn
- ipykernel
- ipython
- matplotlib
- mlxtend
- more-itertools
- numpy
- pandas
- pathos
- pip
- pip:
  - tensorflow-gpu==2.0.0-rc0
- psutil
- pyqt
- pystan
- python-docx
- pytorch
- py-xgboost
- scikit-learn
- scikit-optimize
- scipy
- seaborn
- setuptools
- shap
- sphinx
- sqlalchemy
- statsmodels
- sympy
- yellowbrick
- cudatoolkit
- cudnn
- cuml
- cudf